### ISSUE TITLE
how to read/write btsys_mode

### ISSUE THREAD

**Issue by latonita** [tomaskovacik/OVC3860#12]
Hi, interesting project
however i still not get idea how to read/write specific setting. for example i would like to change `btsys_mode` .
how do i know which raw data to send? 
"key number" for bsys_mode is 7. but how do i know address?
"0x11, 0xc7, 0x00, 0x10 (read module name) we are sending: 0x1* - read data from address 0x01c7, size 0x0010"

unfortunately original config tool doesnt work on my module. neither revD nor revE, so i can't even sniff communication.

thank you

**Comment by latonita** [comment]
so, imagine bsys_mode is 1 byte at address 0x07 (which is questionable).
shall i send
0x10,0x07,0x00,0x01 ?

**Comment by latonita** [comment]
go it! address shall be carefully calculated from data size of all the preceding keys)

**Comment by tomaskovacik** [comment]
basicaly: address is just position, so each 8bit value is +1byte (for example next value after module name is address for value of module name + 16+1 cose name hase 16bytes)

address is max 0x0FFF 

then you highest 4bits coresponding what you want, for read you put ther 1

hope it helps

**Comment by latonita** [comment]
yes, got it :) 
succesfully changed type as i needed, worked like a charm.
until i wanted to change name of module from default 'h166' to 'jeep_wh' and then to 'jeep'
now noone can see this module, even if it is in discoverable mode :( looks like i need to order new one (
i think there were some garbage after 'h166', and i think it wasn't garbage, but some configuration data of my particular revision of module, not compatible with revE datasheet. bad luck

**Comment by tomaskovacik** [comment]
https://github.com/tomaskovacik/kicad-library/tree/master/library/datasheet/OVC3860_based_modules


;) full dumps for revD and revE

The original tool works for full upload for me always, even works for downloading only one value, only one which did not work was serial baudrate.

Good luck

T.

**Comment by latonita** [comment]
thanks. tried to rewrite 16 bytes in 'name' area with data from dat files, didn't help unfortunately.
will try to find a way to load full dump. actually i believe i need to write some code for that )

**Comment by tomaskovacik** [comment]
Try ovc app for it it works for me all times i try it

**Comment by tomaskovacik** [comment]
writeSysBTMode(uint8_t mode) will write this PSkey

parameter should by one of these:

M0 - HCI UART
M3 - HEADSET
M4 - CARKIT
M6 - AVSNK
 M9 - MOBILE

t.

**Comment by Teban89** [comment]
Hi, what is **btsys_mode**? what is its operation? thanks!!

**Comment by tomaskovacik** [comment]
please read datasheet: https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/OVC3860_based_modules/OVC3860_RevE_PSKeys_Setting_v1.2.pdf

it defines  mode of operation of the module, if it acts as a headset, bluetooth2serial interface or other
